import type {GetServerSideProps, NextPage} from 'next'
import Head from 'next/head'
import {Post} from "../../interfaces/Posts";
import Wrapper from "../../components/Wrapper";

const Post: NextPage<Post> = (post) => {
    return (
        <div>
            <Head>
                <title>Post {post.id}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Wrapper>
                <h2>{post.title}</h2>
                <p>{post.body}</p>
            </Wrapper>
        </div>
    )
}


export const getServerSideProps: GetServerSideProps = async (context) => {
    const res = await fetch(`https://jsonplaceholder.typicode.com/posts/${context.query.id}`);
    const post = await res.json();

    return {
        props: post
    }
}


export default Post
