import type {GetStaticProps, NextPage} from 'next'
import Head from 'next/head'
import Wrapper from "../../components/Wrapper";
import Grid from "../../components/Grid";
import {Photo, Photos} from "../../interfaces/Photos";
import Image from "next/image";
import {ImageLoaderProps} from "next/dist/client/image";

const About: NextPage = ({photos}:Photos) => {
    const myLoader = ({ src, width, quality }:ImageLoaderProps) => {
        return `${src}?w=${width}&q=${quality || 75}`
    }

    return (
        <div>
            <Head>
                <title>Next js</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Wrapper>
                <Grid>
                    {photos.slice(0, 9).map((photo:Photo) => (
                        <Image
                            loader={myLoader}
                            alt={photo.title}
                            key={photo.id}
                            src={photo.thumbnailUrl}
                            width={500}
                            height={500}
                        />
                    ))}
                </Grid>
            </Wrapper>
        </div>
    )
}

export const getStaticProps: GetStaticProps = async () => {
    const res = await fetch('https://jsonplaceholder.typicode.com/photos');
    const photos = await res.json();

    return {
        props: {
            photos,
        },
    }
}

export default About
