import type { NextPage } from 'next'
import Head from 'next/head'
import Grid from "../components/Grid";
import Link from "next/link";
import {Post, Posts} from "../interfaces/Posts";
import {GetServerSideProps} from "next";
import Wrapper from "../components/Wrapper";

const Home: NextPage = ({posts}:Posts) => {
  return (
    <div>
      <Head>
        <title>Next js</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Wrapper>
          <Grid>
              {posts.map((post:Post) => (
                  <Link href={{
                      pathname: '/posts/[id]',
                      query: { id: post.id },
                  }}
                  key={post.id}>
                      {post.title}
                  </Link>
              ))}
          </Grid>
      </Wrapper>
    </div>
  )
}

export const getServerSideProps: GetServerSideProps = async () => {
    const res = await fetch('https://jsonplaceholder.typicode.com/posts');
    const posts = await res.json();

    return {
        props: {
            posts,
        },
    }
}

export default Home
